services:
  - type: web
    name: Tawasl-
    env: node
    buildCommand: |
      npm install
      npm run build
      python3.11 -m pip install --upgrade pip
      python3.11 -m pip install -r server/ai-scripts/requirements.txt
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11
      - key: PYTHONPATH
        value: /opt/render/project/src/server/ai-scripts 
