services:
  - type: web
    name: Tawasl-
    env: node
    buildCommand: |
      apt-get update && apt-get install -y python3 python3-distutils python3-pip
      npm install
      npm run build
      python3 -m pip install --upgrade pip
      python3 -m pip install -r server/ai-scripts/requirements.txt
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: PYTHONPATH
        value: /opt/render/project/src/server/ai-scripts 
